name: remove-cluster

on:
  workflow_dispatch:
    inputs:
      s3_storage:
        description: 'Name AWS S3 storage bucket'
        required: true
        default: 'ocp-s3-storage'
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
      region:
        description: 'AWS Region to deploy cluster to'
        required: true
        default: 'us-east-1'          
      clusterConfigName:
        description: 'Name of cluster config in S3 to pull down and destroy'
        required: true

jobs:
  remove-openshift-cluster:
    runs-on: macos-latest
    env:
      temp_dir: "temp-${{ github.run_number }}"
    steps:
      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Install OpenShift CLI
        uses: redhat-actions/oc-installer@v1

      - name: Download OpenShift installer and update permissions
        shell: bash
        env:
          s3_installer_path: "${{ github.event.inputs.s3_storage }}/macos-installer"
        run: |
          mkdir -p ./${{ env.temp_dir }}
          echo "Downloading OpenShift Installer..."
          aws s3 cp s3://${{ env.s3_installer_path }}/openshift-install ./openshift-install --region ${{ github.event.inputs.region }} --quiet
          echo "Update permissions to executable on the openshift-installer..."
          chmod +rwx ./openshift-install

      - name: Get cluster metadata files from S3
        shell: bash
        run: |
          mkdir -p ./${{ env.temp_dir }}
          echo "Downloading ${{ github.event.inputs.clusterConfigName }} metadata files from S3..."
          aws s3 sync s3://${{ github.event.inputs.s3_storage }}/${{ github.event.inputs.clusterConfigName }} ./${{ env.temp_dir }} --region ${{ github.event.inputs.region }} 

      - name: Destroy cluster
        shell: bash
        run: |
           ./openshift-install destroy cluster --dir=./${{ env.temp_dir }}